# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on: # which events the pipeline 
  push: # pushing the master branch
    branches: [ main ]
  pull_request: # pull request from the master branch
    branches: [ main ]

jobs:
  build-java: # job name

    runs-on: macOS-latest # OS 
    
    steps:
    - uses: actions/checkout@v2 # pull repository                                                           

    - name: Set up JDK 1.8
      uses: actions/setup-java@v1 # install java env
      with:
        java-version: 1.8

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build with Gradle
      run: ./gradlew build
      
    - uses: docker-practice/actions-setup-docker@master
    - run: set -x

    - name: Build and Push Docker Image
      uses: mr-smithers-excellent/docker-build-push@v4
      with:
        image: drerdemsezgin/flask-app
        registry: docker.io
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
       
